const fs = require('fs')

exports.fatos = [
  "Estima-se que, a cada ano, o monte Everest cresça 4 milímetros.",
  "A cada minuto, cerca de 72 horas de conteúdo são enviados ao site de vídeos Youtube.",
  "A barragem da maior usina hidrelétrica do mundo, a Usina das Três Gargantas, localizada na China, prolongaria a duração do dia em 0,66 microssegundos se operasse em sua capacidade máxima. Isso ocorreria em virtude da enorme massa de água que ela comporta.",
  "Durante o fenômeno Superlua, calcula-se que o diâmetro lunar possa aumentar em até 14%.",
  "Há uma lâmpada que permanece ligada continuamente há mais de 113 anos na cidade de Livermore, na Califórnia.",
  "O cérebro humano é formado por, aproximadamente, 75% de água.",
  "O cachorro-quente é uma invenção alemã do século XV.",
  "Alguns animais, como os cangurus, não param de crescer mesmo atingindo a idade adulta.",
  "A maioria das vacas não consegue descer escadas.",
  "Em média, um adulto respira 550 litros de oxigênio puro diariamente.",
  "Estima-se que 4% da população mundial seja canhota.", 
  "A maior palavra da língua portuguesa refere-se a uma doença causada pela respiração de cinzas vulcânicas: pneumoultramicroscopicossilicovulcanoconiótico.",
  "O Brasil é o país que possui a maior comunidade japonesa fora do Japão. Só em São Paulo, moram mais de 600 mil japoneses.",
  "O calendário da Etiópia é sete anos atrasado em relação aos demais países do ocidente.",
  "A avenida mais larga do mundo, com 14 faixas diferentes, fica na Argentina.",
  "Mais de 10% de toda a biodiversidade do mundo é encontrada no continente australiano.",
  "A Rússia é o maior país do mundo, ocupando cerca de 10% de toda a terra do planeta.",
  "Na Holanda, estima-se que o número de bicicletas ultrapasse três vezes o número de veículos.",
  "O menor país do mundo é o Vaticano, com cerca de 800 habitantes oficiais.",
  "Mais de 10% de toda a biodiversidade do mundo é encontrada no continente australiano.",
  "A Rússia é o maior país do mundo, ocupando cerca de 10% de toda a terra do planeta.",
  "Na Holanda, estima-se que o número de bicicletas ultrapasse três vezes o número de veículos.",
  "O menor país do mundo é o Vaticano, com cerca de 800 habitantes oficiais.",
  "O Sol converte cerca de 600 milhões de toneladas de hidrogênio em hélio a cada segundo em virtude do processo de fusão nuclear.",
  "Um volume do tamanho da cabeça de um alfinete feito do material de uma estrela de nêutrons teria uma massa de 1 milhão de toneladas.",
  "A parte mais profunda do oceano chega a 11 mil metros.",
  "O esqueleto humano é formado por 206 ossos, no entanto, os bebês nascem com cerca de 270 ossos, que se fundem em ossos maiores.",
  "A Terra orbita o Sol a uma velocidade de, aproximadamente, 107 mil km/h.",
  "O corpo humano tem mais de 96 mil km de vasos sanguíneos.",
  "Estima-se que o Universo conte com mais de 10 bilhões de galáxias.",
  "A luz do Sol leva cerca de 8 minutos e 20 segundos para chegar à Terra.",
  "O dia tem, aproximadamente, 23 horas e 56 minutos, não 24 horas. Por isso, a cada quatro anos, adicionamos um dia ao mês de fevereiro. Esses anos são chamados de bissextos.",
  "O recorde de voo de uma galinha é de 13 segundos.",
  "Os mosquitos são os animais mais letais do mundo, causando mais mortes humanas do que todas as guerras da história. Esses seres vivos matam cerca de 725 mil humanos anualmente.",
  "Uma pulga pode saltar até 350 vezes sua altura.",
  "As formigas são capazes de levantar até 50 vezes seu próprio peso.",
  "Todos os mamíferos são capazes de saltar, menos os elefantes.",
  "Girafas não têm cordas vocais.",
  "A língua de uma baleia-azul pode pesar até 3,6 toneladas, o equivalente ao peso de um elefante médio.",
  "As borboletas têm cerca de 12 mil olhos.",
  "Os vertebrados mais longevos do mundo são os tubarões da Groenlândia, que podem viver cerca de 400 anos.",
  "Existem algumas árvores vivas espalhadas pelo mundo que têm, pelo menos, 5000 anos de idade.",
  "Os ursos-polares são, praticamente, invisíveis pelas câmeras de calor em virtude da eficiente camada de gordura isolante que os protege do frio.",
  "A palavra “brasil” significa “vermelho como brasa”.",
  "O Brasil é o maior produtor de café do mundo.",
  "O Brasil é também o país que mais desmata a natureza em todo o mundo.",
  "O Brasil tem a maior biodiversidade do mundo graças à Floresta Amazônica.",
  "Das 30 cidades mais violentas do mundo, 12 estão localizadas no Brasil.",
  "Toda moeda circulante e oficial do Brasil é produzida na Casa da Moeda, no Rio de Janeiro.",
  "Tocantins é o estado mais novo do Brasil, fundado em 1988.",
  "A feijoada é considerada o prato nacional do Brasil.",
  "O verbo “testemunhar” é baseado nos tribunais romanos onde os homens juravam pelos testículos sobre alguma declaração.",
  "O pintor Vincent Van Gogh vendeu apenas uma pintura quando ainda estava vivo: Red Vineyard at Arles.",
  "Uma cobra píton grande o suficiente, é capaz de engolir uma cabra inteira, ou coisas piores...",
  
  "A primeira forma de escrita conhecida pela humanidade foi a escrita cuneiforme, desenvolvida pelos sumérios, na Mesopotâmia.",
  "Os primeiros europeus a pisarem na América foram os vikings, que chegaram no Canadá por volta do ano 1000.",
  "Quando D. Pedro I anunciou a independência do Brasil, em 7 de setembro de 1822, ele sofria de problemas intestinais causados por consumo de água ou comida contaminada.",
  "Vidkun Quisling foi um norueguês que colaborou para que seu país fosse invadido pela Alemanha durante a Segunda Guerra Mundial. O termo quisling entrou para o dicionário inglês como sinônimo de traidor.",
  "Estima-se que cerca de 35 mil brasileiros tenham falecido entre 1918 e 1919 por conta da gripe espanhola.",
  "Carlos Luz foi o presidente do Brasil que menos tempo ficou no cargo. O mandato dele durou apenas três dias.",
  "Os moais são construções megalíticas construídas pelos rapa nui na Ilha de Páscoa, e o moai mais pesado tem cerca de 75 toneladas.",
  "A primeira cidade fundada pelos portugueses no Brasil foi a cidade de São Vicente, em 1532.", 
  "Os povos celtas ficaram assim conhecidos porque os gregos deram-lhes o nome genérico de “keltoi”.",
  "O monarca absolutista com o reinado mais longo foi Luís XIV, possuindo um reinado de 72 anos de duração.",
  "Fundada em julho de 1994, pelo engenheiro e ex-CEO Jeff Bezos, a Amazon foi inicialmente registrada como Cadabra.Inc. A ideia era fazer uma referência à palavra mágica “Abracadabra”. No entanto, quando o primeiro advogado de Bezos leu o nome pela primeira vez, alertou o empresário de que a associação não soava tão clara assim. Além disso, algumas pessoas confundiam o nome com a palavra “cadáver”.",
  "Chamado de “WorldWideWeb”, o primeiro navegador da história foi criado em 1990 por Tim Berners-Lee, cientista de computação britânico.",
  "O primeiro spam foi enviado há 44 anos, em 1978. A mensagem em massa foi disparada por Gary Thuerk, gerente de marketing da ARPANET, para promover um novo modelo de computador. Cerca de 400 clientes potenciais receberam a mensagem. Apesar de ter arrecadado US$ 13 milhões (cerca de R$ 69,7 milhões em conversão direta) em vendas, a empresa também recebeu muitas ligações de pessoas reclamando dos e-mails indesejados."
]